# Generated by Django 5.1.2 on 2026-05-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=300)),
                ('film_cover', models.URLField(max_length=500)),
                ('release_date', models.DateField()),
                ('description', models.TextField()),
                ('genre', models.CharField(db_index=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-release_date',),
            },
        ),
    ]
